// Post action types
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const REQUEST_SAVE_POST = 'REQUEST_SAVE_POST'
export const REQUEST_POST = 'REQUEST_POST'
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST'
export const RECEIVE_DELETE_POST = 'RECEIVE_DELETE_POST'
export const DELETE_POST = 'DELETE_POST'
export const REQUEST_UPDATE_POST = 'REQUEST_UPDATE_POST'
export const RECEIVE_UPDATE_POST = 'RECEIVE_UPDATE_POST'
export const TOGGLE_POST_FORM = 'TOGGLE_POST_FORM'
export const CLOSE_POST_FORM = 'CLOSE_POST_FORM'
export const SORT_POSTS = 'SORT_POSTS'

// Comment action types
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const REQUEST_SAVE_COMMENT = 'REQUEST_SAVE_COMMENT'
export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT'
export const RECEIVE_DELETE_COMMENT = 'RECEIVE_DELETE_COMMENT'
export const REQUEST_UPDATE_COMMENT = 'REQUEST_UPDATE_COMMENT'
export const RECEIVE_UPDATE_COMMENT = 'RECEIVE_UPDATE_COMMENT'

// Vote action types
export const REQUEST_UP_VOTE = 'REQUEST_UP_VOTE'
export const REQUEST_DOWN_VOTE = 'REQUEST_DOWN_VOTE'
export const RECEIVE_VOTE = 'RECEIVE_VOTE'